service: FinancialTrackerAPI
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: 'us-east-2'
  iam:
    role:
      statements:
      - Effect: Allow
        Action:
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
        Resource: arn:aws:dynamodb:us-east-2:537778070242:table/users-FTAPI
      - Effect: Allow
        Action:
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
        Resource: arn:aws:dynamodb:us-east-2:537778070242:table/transactions-FTAPI


resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users-FTAPI
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
    TransactionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: transactions-FTAPI
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: IdUser
            AttributeType: S
          - AttributeName: TRANSACTION_ID
            AttributeType: S
        KeySchema:
          - AttributeName: IdUser
            KeyType: HASH
          - AttributeName: TRANSACTION_ID
            KeyType: RANGE



functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  signup:
    handler: auth.signup
    events:
      - httpApi:
          path: /auth/signup
          method: post
  signin:
    handler: auth.signin
    events:
      - httpApi:
          path: /auth/signin
          method: post
  signin2:
    handler: auth.signin2
    events:
      - httpApi:
          path: /signin2
          method: get
  createTransaction:
    handler: transactions.create
    events:
      - httpApi:
          path: /transaction/create
          method: post
  editTransaction:
    handler: transactions.edit
    events:
      - httpApi:
          path: /transaction/edit
          method: get
  deleteTransaction:
    handler: transactions.delete
    events:
      - httpApi:
          path: /transaction/delete/{id}
          method: get
          
