service: FinancialTrackerAPI
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: 'us-east-2'

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  signup:
    handler: users.signup
    events:
      - httpApi:
          path: /signup
          method: get
